---
title: "SI_table_species"
output: html_document
---

```{r setup, include=FALSE}

library(data.table)
library(tidyverse)

knitr::opts_chunk$set(echo = TRUE)
```

## Supporting table 1: SPECIES

```{r si t1}

## Load species summary
spp_summary <- fread(here("_data/combined_spp_summary.csv"))
names(spp_summary)

## make spp groups
spp_summary <- spp_summary %>%
  mutate(tax_group_2 = case_when(
    phylum %in% c("CHLOROPHYTA", "RHODOPHYTA") ~ "Algae",
    phylum == "ARTHROPODA" ~ "Arthropods",
    phylum %in% c("CNIDARIA","CTENOPHORA") ~ "Cnidarians & Ctenophores",
    phylum == "ECHINODERMATA" ~ "Echinoderms",
    class %in% c("ACTINOPTERYGII","SARCOPTERYGII") ~ "Fish (ray & lobe-finned)",
    class %in% c("CEPHALASPIDOMORPHI","CEPHALOCHORDATA","MYXINI") ~ 
      "Jawless fish & Lancelets",
    phylum %in% c("BRACHIOPODA","BRYOZOA","KAMPTOZOA","PHORONIDA") ~ "Lophophores",
    class == "MAMMALIA" ~ "Mammals",
    class == "REPTILIA" ~ "Reptiles",
    phylum == "MOLLUSCA" ~ "Mollusks",
    class == "AVES" ~ "Seabirds",
    class %in% c("CHONDRICHTHYES","ELASMOBRANCHII","HOLOCEPHALI") ~ "Sharks, Rays, Chimaeras",
    phylum == "PORIFERA" ~ "Sponges",
    class %in% c("APPENDICULARIA","ASCIDIACEA","THALIACEA") ~ "Tunicates",
    phylum == "TRACHEOPHYTA" ~ "Vascular plants",
    phylum %in% c("ACANTHOCEPHALA","ANNELIDA","CHAETOGNATHA","CYCLIOPHORA","ECHIURA",
    "GASTROTRICHA","GNATHOSTOMULIDA","HEMICHORDATA","LORICIFERA","NEMERTEA","PLATYHELMINTHES",
    "PRIAPULIDA","ROTIFERA","SIPUNCULA") ~ "Worms & microscopic animals",
    TRUE ~ "Other"
    ))

spp_tbl <- spp_summary %>%
  dplyr::select(c("sciname", "class", "num_eez", "category", "tax_group_2")) %>%
  arrange(desc(num_eez)) %>%
  top_n(100, num_eez)

```

## Supporting table 2: COUNTRIES 

```{r si t2}

## wgi scores
wdi_scores <- fread(here("_data/combined_eez_summary_wdi_scores.csv"))
names(wdi_scores)
wdi <- wdi_scores %>%  dplyr::select(c(score,rgn_id_2,rgn_name_short))

## get country area info
dat_area <- fread(here("_data/combined_eez_summary_areas.csv"))
names(dat_area)

## add ranks
dat_all <- dat_area %>%
  mutate(tb_km2 = num_spp_tb/rgn_area_km2,
         rank_tb_km2 = dense_rank(-tb_km2),
         rank_tb = dense_rank(-num_spp_tb)) 

dat_all %>% arrange(rank_tb_km2)

dat_all <- left_join(dat_all, wdi, by = "rgn_id_2")

names(dat_all)

dat_all <- dat_all %>% dplyr::select(-c(rgn_id_2, num_spp_sc_th)) %>% arrange(num_spp_tb)

```

