---
title: "tb_map_by_cell"
output: html_document
---

## Summary

Here I make a two-panel figure showing a map of A) the density of transboundary species PER CELL and B) the density of transboundary threatened species PER CELL (if they look exactly the same then comment on that and only include map A, and put map B in the SI).

A later version may show the number of tb species in each cell * the number of cells or EEZs that species appears in, to distinguish the "very transboundary" species from those spanning a few jurisdictions

For the main analysis, we use the 10cell cutoff for occurrence in an EEZ. This species summary was prepared in "transboundar_explore_am", "transboundary_explore_iucn", "combine_am_iucn_results", then "tax_explore" (added taxonomic detail and made final summary file)

Some good resources:
https://rawgit.com/eco-data-science/spatial-analysis-R/gh-pages/intro_spatial_data_R.html (tutorial from Jaimie)


```{r setup, include=FALSE}

library(raster)
library(tidyverse)
library(here)
library(data.table)
# library(rasterVis) # install.packages("rasterVis")
library(RColorBrewer)
library(tmap)

```

##  First make map of all TB species by cell

Take raster layer made in QGIS (reassigning disputed ids, CCAMLR, ABNJ in the vector file) which I converted to a raster in R

```{map all tb by cell}

#<><><><><><
## Load raster layer 

cell_id_rast <- raster::raster("R:\\TRANSSPP-A2259\\transboundary_species_v02\\_spatial_v02\\cell_id_rast.tif")
cell_id_rast
plot(cell_id_rast)

#<><><><><><>
## Load species summary

cell_summary_combined <- fread("R:\\TRANSSPP-A2259\\tb_spp_v04\\combined_cell_summary.csv")
names(cell_summary_combined)
summary(cell_summary_combined)

## <><><><> tb species richness

cells_tb_spp_rich <- cell_summary_combined %>%
  dplyr::select(cell_id, num_spp_tb) %>%
  as.data.frame()
summary(cells_tb_spp_rich)

## rasterize
subs(cell_id_rast, cells_tb_spp_rich, by = 1, which = 2, subsWithNA=T, 
     filename= "R:\\TRANSSPP-A2259\\tb_spp_v04\\_spatial_v04\\tb_cells_rich_rast.tif")

## <><>>< Percent TB species 

# cells_tb_perc <- cell_summary_combined %>%
 # dplyr::select(cell_id, perc_tb) %>%
 # as.data.frame()

# subs(cell_id_rast, cells_tb_perc, by = 1, which = 2, subsWithNA=T, 
    # filename= "R:\\TRANSSPP-A2259\\transboundary_species_v02\\_v03_spatial\\perc_tb_cells_rast.tif")

#<><><> tb species weighted
# ** Not using this map anymore

# cells_tb_spp_wgt <- cells_tb_spp %>%
  # dplyr::select(cell_id, tb_cell_score) %>% # or whatever I called it
  # as.data.frame()
# summary(cells_tb_spp_wgt)

# subs(cell_id_rast, cells_tb_spp_wgt, by = 1, which = 2, subsWithNA=T,
   #  filename="R:\\TRANSSPP-A2259\\transboundary_species_v02\\_spatial_v02\\tb_cells_wgt_rast.tif",
   #  overwrite = TRUE)

```

## Plot all species

```{plot all spp}

#<>><>< All species richness

rast <- raster::raster("R:\\TRANSSPP-A2259\\tb_spp_v04\\_spatial_v04\\tb_cells_rich_rast.tif")
rast
plot(rast)

p <- tm_shape(rast) +
  tm_raster(palette = "Blues", 
            style = "cont",
            # style = "log10_pretty",
            # style = "log10",
            legend.show = TRUE,
            title = "Number tb \nspecies") + # legend title
  tm_layout(main.title = "Transboundary species richness by cell",
            main.title.size = 1,
            frame = TRUE, # inner.margins = c(0,.0,.05,.0), asp = 1.5,
            legend.title.size = 0.8,
            legend.text.size = 0.5, 
            legend.outside=TRUE, legend.outside.position = 'right',
            legend.frame = FALSE)
  
p
# tmap_save(tm = p, filename = "_results/figs/analysis_v02/spp_density_map/tb_rich_log10.png", dpi = 300)
# tmap_save(tm = p, filename = "_results/figs/analysis_v02/spp_density_map/tb_rich_log10pretty.png", dpi = 300)
tmap_save(tm = p, filename = "_results/figs/analysis_v02/spp_density_map/tb_rich_latlon.png") # default dpi = 300

#<><><>>< All species percent TB

perc_rast <- raster::raster("R:\\TRANSSPP-A2259\\transboundary_species_v02\\_v03_spatial\\perc_tb_cells_rast.tif")

p <- tm_shape(perc_rast) +
  tm_raster(palette = "Blues", 
            style = "cont",
            # style = "log10_pretty",
            # style = "log10",
            legend.show = TRUE,
            title = "Percent tb \nspecies") + # legend title
  tm_layout(main.title = "Percent tb species by cell",
            main.title.size = 1,
            frame = TRUE, # inner.margins = c(0,.0,.05,.0), asp = 1.5,
            legend.title.size = 0.8,
            legend.text.size = 0.5, 
            legend.outside=TRUE, legend.outside.position = 'right',
            legend.frame = FALSE)
  

#<><><>< All species weighted 

# rast2 <- raster::raster("R:\\TRANSSPP-A2259\\transboundary_species_v02\\_spatial_v02\\tb_cells_wgt_rast.tif")

# p2 <- tm_shape(rast2) +
#  tm_raster(palette = "Blues",
         #   style = "cont",
            # style = "log10_pretty",
            # style = "log10",
        #    legend.show = TRUE)
# p2 # look the same as the richness ones to me
# tmap_save(tm = p2, filename = "_results/figs/analysis_v02/spp_density_map/tb_rich_latlon_wgt.png") 

```

## Reproject as Mollweide

NB projectRaster() only accepts the lengthy proj4string definitions of a CRS rather than concise EPSG codes.

```{mollweide}

# define mollweide projection
mollweide <- "+proj=moll +lon_0=-90 +x_0=0 +y_0=0 +ellps=WGS84"
# centered on pacific 
mollweide_pac <- "+proj=moll +lon_0=150 +x_0=0 +y_0=0 +ellps=WGS84"

## project rasters to mollweide

rast_moll <- projectRaster(rast, crs = mollweide, method = "ngb")
# Warning message: In rgdal::rawTransform(projto_int, projfrom, nrow(xy), xy[, 1],  : 1204440 projected point(s) not finite
    # this is ok: some data were lost, depending on projection - it's probably at the edges of hte cells
rast_moll <- trim(rast_moll)

rast_moll_pac <- projectRaster(rast, crs = mollweide_pac, method = "ngb")
rast_moll_pac <- trim(rast_moll_pac)

plot(rast_moll_pac)

# writeRaster(rast_moll, "R:\\TRANSSPP-A2259\\transboundary_species_v02\\_v03_spatial\\tb_cells_rich_rast_moll.tif")
writeRaster(rast_moll_pac, "R:\\TRANSSPP-A2259\\tb_spp_v04\\_spatial_v04\\tb_cells_rich_rast_mollpac.tif")

## plot and save

p3 <- tm_shape(rast_moll_pac) +
  # tm_shape(rast_moll) +
  tm_raster(palette = "Blues", 
            style = "cont",
            breaks = seq(0,8000,1000),
            legend.show = TRUE,
            title = "Number tb \nspecies") + # legend title
  tm_layout(# main.title = "Transboundary species richness by cell",
            # main.title.size = 0.9,
            frame = TRUE, # inner.margins = c(0,.0,.05,.0), asp = 1.5,
            legend.title.size = 0.8,
            legend.text.size = 0.5, 
            legend.outside=TRUE, legend.outside.position = 'right',
            legend.frame = FALSE)
p3
tmap_save(tm = p3, filename = "_results/figs/analysis_v04/fig_tb_rich_moll_pac.png",
          width = 7, height = 4, units = "in") 

#<><><>< 
## proportion tb species per cell

perc_rast_moll <- projectRaster(perc_rast, crs = mollweide, method = "ngb")
# Warning message: In rgdal::rawTransform(projto_int, projfrom, nrow(xy), xy[, 1],  : 1204440 projected point(s) not finite
perc_rast_moll <- trim(perc_rast_moll)

writeRaster(perc_rast_moll, "R:\\TRANSSPP-A2259\\transboundary_species_v02\\_v03_spatial\\perc_tb_cells_rast_moll.tif")

perc_rast_moll_pac <- projectRaster(perc_rast, crs = mollweide_pac, method = "ngb")
perc_rast_moll_pac <- trim(perc_rast_moll_pac)

writeRaster(perc_rast_moll_pac, "R:\\TRANSSPP-A2259\\transboundary_species_v02\\_v03_spatial\\perc_tb_cells_rast_mollpac.tif")

p4 <- tm_shape(perc_rast_moll_pac) +
  # tm_shape(perc_rast_moll) +
  tm_raster(palette = "Blues", 
            style = "cont",
            legend.show = TRUE,
            title = "Number tb \nspecies") + # legend title
  tm_layout(main.title = "Transboundary species richness by cell",
            main.title.size = 0.9,
            frame = TRUE, # inner.margins = c(0,.0,.05,.0), asp = 1.5,
            legend.title.size = 0.8,
            legend.text.size = 0.5, 
            legend.outside=TRUE, legend.outside.position = 'right',
            legend.frame = FALSE)

tmap_save(tm = p4, filename = "R:\\TRANSSPP-A2259\\transboundary_species_v02\\_v03_results\\perc_tb_moll_pac.png") 
#<><><><><>><
## weighted tb cell score

# rast_wgt_moll_pac <- projectRaster(rast2, crs = mollweide_pac, method = "ngb")
# rast_wgt_moll_pac <- trim(rast_wgt_moll_pac)

# writeRaster(rast_wgt_moll_pac, "R:\\TRANSSPP-A2259\\transboundary_species_v02\\_spatial_v02\\tb_cells_score_rast_mollpac.tif")

# p4 <- tm_shape(rast_wgt_moll_pac) +
 #  tm_raster(palette = "Blues", 
         #   style = "cont",
          #  legend.show = TRUE,
          #  title = "Tb species\nscore") + # legend title
 # tm_layout(main.title = "Weighted transboundary species richness by cell",
         #   main.title.size = 0.9,
         #   frame = FALSE, # inner.margins = c(0,.0,.05,.0), asp = 1.5,
         #   legend.title.size = 0.8,
         #   legend.text.size = 0.5, 
         #   legend.outside=TRUE, legend.outside.position = 'right',
         #   legend.frame = FALSE)
# p4 # nb "min" = million
# tmap_save(tm = p4, filename = "_results/figs/analysis_v02/spp_density_map/tb_score_moll_pac.png") 

```

## Then map only Th TB species per cell

```{map tb th by cell}

# Load df of threatened tb species per cell

cells_tb_spp_th <- fread("R:\\TRANSSPP-A2259\\tb_spp_v04\\iucn_spp_cell_summary_thr_tb.csv")
names(cells_tb_spp_th)

#<><>< th tb species richness
cells_tb_spp_th_rich <- cells_tb_spp_th %>%
  dplyr::select(cell_id, num_spp_tb) %>%
  as.data.frame()

subs(cell_id_rast, cells_tb_spp_th_rich, by = 1, which = 2, subsWithNA=T, 
     filename= "R:\\TRANSSPP-A2259\\tb_spp_v04\\_spatial_v04\\th_tb_cells_rich_rast.tif")

rast2 <- raster::raster("R:\\TRANSSPP-A2259\\tb_spp_v04\\_spatial_v04\\th_tb_cells_rich_rast.tif")

#<><><>< mollweide pacific centered projection

mollweide_pac <- "+proj=moll +lon_0=150 +x_0=0 +y_0=0 +ellps=WGS84"

rast_moll_pac <- projectRaster(rast2, crs = mollweide_pac, method = "ngb")
rast_moll_pac <- trim(rast_moll_pac)

plot(rast_moll_pac)

writeRaster(rast_moll_pac, "R:\\TRANSSPP-A2259\\tb_spp_v04\\_spatial_v04\\th_tb_cells_rich_rast_mollpac.tif")

#<><>< th tb species weighted
# cells_tb_spp_th_wgt <- cells_tb_spp_th %>%
 #  dplyr::select(cell_id, cell_score) %>%
 # as.data.frame()

# subs(cell_id_rast, cells_tb_spp_th_wgt, by = 1, which = 2, subsWithNA=T, 
    # filename= "R:\\TRANSSPP-A2259\\transboundary_species_v02\\_spatial\\th_tb_cells_wgt_rast.tif")
#<>><><><>
```

## Plot threatened TB species

```{plot thr spp}

#<>><>< Threateend species richness

rast3 <- raster::raster("R:\\TRANSSPP-A2259\\tb_spp_v04\\_spatial_v04\\th_tb_cells_rich_rast_mollpac.tif")
rast3

## plot

p3 <- tm_shape(rast3) +
  tm_raster(palette = "Purples", 
            style = "cont",
            breaks = seq(0,250,25),
            legend.show = TRUE,
            title = "Number Th.\ntb species") + # legend title
  tm_layout(# main.title = "Threatened transboundary species richness by cell",
            # main.title.size = 0.9,
            frame = FALSE, # inner.margins = c(0,.0,.05,.0), asp = 1.5,
            legend.title.size = 0.8,
            legend.text.size = 0.5, 
            legend.outside=TRUE, legend.outside.position = 'right',
            legend.frame = FALSE)
p3

tmap_save(tm = p3, filename = "_results/figs/analysis_v04/thr_tb_rich_moll_pac.png", dpi = 300)


#<><><>< thraetened species weighted score

## reproject
rast4 <- raster::raster("R:\\TRANSSPP-A2259\\transboundary_species_v02\\_spatial_v01\\th_tb_cells_wgt_rast.tif")

rast4_moll_pac <- projectRaster(rast4, crs = mollweide_pac, method = "ngb")
rast4_moll_pac <- trim(rast4_moll_pac)

## save
writeRaster(rast4_moll_pac, "R:\\TRANSSPP-A2259\\transboundary_species_v02\\_spatial_v02\\thr_tb_cells_score_rast_mollpac.tif")

## plot
p4 <- tm_shape(rast4_moll_pac) +
  tm_raster(palette = "Purples", 
            style = "cont",
            legend.show = TRUE,
            title = "Score Th.\ntb species") + # legend title
  tm_layout(main.title = "Threatened transboundary species score by cell",
            main.title.size = 0.9,
            frame = FALSE, # inner.margins = c(0,.0,.05,.0), asp = 1.5,
            legend.title.size = 0.8,
            legend.text.size = 0.5, 
            legend.outside=TRUE, legend.outside.position = 'right',
            legend.frame = FALSE)
p4 # also lookds like the richness map

tmap_save(tm = p4, filename = "_results/figs/analysis_v02/spp_density_map/thr_tb_score_moll_pac.png", dpi = 300)

```

