---
title: "fig_EEZ_range"
output: html_document
---

## Summary

Here I make many versions of Fig 1, including:

1) a histogram/ stacked bar chart with number of EEZs or regions on the X axis (discrete scale) and number of species matching that number of countries on the y axis (discrete scale), divided by color (a la stacked bar) into verts, inverts, plants 
An alternate version has the bars colored by conservation category (Th, Not threatened, DD/Not assessed)

2) the same plot but with the y axis showing the proportion of all species with that number of jurisdictions instead of the raw count

3) Bec's suggestion with the x axis showing threat groups (including not assessed and data deficient), the y axis showing proportion of the species in that category that are single country versus transboundary. This doesn't show the spread of hte number of EEZs, but I can report that result in the text (e.g., 50% of species are in more than 5 EEZs...)

```{r setup, include=FALSE}

library(here)
library(tidyverse)
#library(forcats) # part of tidyverse
library(scales) # for percentage scales
library(RColorBrewer)
library(gridExtra)
library(cowplot)
#library(ggstance) # don't need with ggplot2 3.3
#library(stringr) # part of tidyverse

```

## Option 6: Grouped stacked bar plot

Here instead of a butterfly, I put both EEZ bins and threat categories on the same panel:
For each phylum, the threat category bar goes below the EEZ bins bar, but with each EEZ bin subdivided by threat category

Like this:
https://stackoverflow.com/questions/46597278/how-to-plot-a-stacked-and-grouped-bar-chart-in-ggplot
but with the second bar grouped by the phylum ANd by the first variable

```{grouped stacked bar v01}

## Load species summary
spp_summary <- fread("R://TRANSSPP-A2259//tb_spp_v04//combined_spp_summary.csv")
names(spp_summary)

# make bins 
spp_summary$eez_bins_1 <- cut(spp_summary$num_eez, 
                              breaks = c(1,2,3,10,20,100,221), 
                            include.lowest = TRUE, right = FALSE, ordered_result = TRUE) # lowest breaks val should be included; breaks closed on right& open on left
# make other bins 
spp_summary$eez_bins_2 <- cut(spp_summary$num_eez, 
                              breaks = c(1,2,3,10,25,51,221), 
                            include.lowest = TRUE, right = FALSE, ordered_result = TRUE)

##<><><>< make plot dat with percentages by eez_bin and threat group
cat_plot <- spp_summary %>% 
  group_by(phylum, eez_bins_2, category) %>%
  summarise(perc_cat_bin = n()) %>%
  group_by(phylum, eez_bins_2) %>%
  mutate(perc_cat_bin = round(perc_cat_bin/sum(perc_cat_bin)*100,2)) %>%
  ungroup()

## reorder factor
cat_plot$category <- forcats::as_factor(cat_plot$category)
levels(cat_plot$category)
cat_plot$category <- fct_relevel(cat_plot$category, "CR","EN","VU","NT","LC","DD","None")


##<><><>< make plot dat with percentages by eez bins

eez_plot <- spp_summary %>% 
  group_by(phylum, eez_bins_2) %>%
  summarise(perc_eez = n()) %>%
  group_by(phylum) %>%
  mutate(perc_eez = perc_eez/sum(perc_eez)*100)

eez_plot$eez_bins_2 <- forcats::as_factor(eez_plot$eez_bins_2)
levels(eez_plot$eez_bins_2)

## Join dfs

names(eez_plot)
names(cat_plot)

combined_plotdat <- left_join(cat_plot, eez_plot, by = c("phylum", "eez_bins_2"))

write_csv(combined_plotdat, here("_data/figs/phyla_bins/fig1_phyla_subdivide_dat.csv"))


#### 1. threat categories plot - subdivided by eez bins

combined_plotdat <- read_csv("_data\figs\phyla_bins\fig1_phyla_dat.csv")

names(combined_plotdat)
levels(combined_plotdat$category)
#threats_palette <- c("white","#bdbdbd","#fef0d9","#fdcc8a","#fc8d59","#e34a33","#b30000")
threats_palette <- c("#b30000", "#e34a33", "#fc8d59", "#fdcc8a", "#fef0d9","#bdbdbd","white")

barwidth = 0.3
gg_cats <- ggplot(data = combined_plotdat) +
  # plot phylum alphabetically from top, with black lines around bars
  geom_bar(aes(x= fct_rev(phylum), y=perc_eez, fill=eez_bins_2), 
           colour="black", position="fill", stat="identity", width = barwidth, size = 0.1) +
  scale_fill_manual(values = c("navyblue","royalblue3","dodgerblue1","deepskyblue1","skyblue1","lightblue1"),
                    labels = c("51-220","25-50","10-24","3-9","2","1"),
                    guide = guide_legend(reverse= TRUE)) +
  geom_bar(aes(x= fct_rev(phylum), y=perc_cat_bin, fill=category), 
           colour="black", position="fill", stat="identity", width=barwidth, size = 0.1) +
  scale_fill_manual(values = threats_palette,
                    labels = c("CR","EN","VU","NT","LC","DD","NA"),
                    #labels = c("NA","DD","LC","NT","VU","EN","CR"),
                    guide = guide_legend(reverse= FALSE)) +
  scale_y_continuous('',labels = percent, expand = c(0,0)) +
  coord_flip() +
  labs(x = NULL) +
  theme(panel.grid.minor = element_blank(),
         panel.grid.major = element_blank(), 
         axis.title.y = element_blank(),
         axis.title.x = element_blank(),
         axis.ticks = element_blank(),
         legend.position = "right",
         plot.margin= unit(c(1, 0, 0, 0), "lines"))
## Scale for 'fill' is already present. Adding another scale for 'fill', which will replace the existing scale. Error: Insufficient values in manual scale. 13 needed but only 7 provided

#<><><><<><><><>

#<>><> Plot with categories per phylum instead of per phylum/ eez bin
## combine bars in illustrator 
# with gaps inbetween bars

library(cowplot)
library(gridExtra)
library(stringr)
library(ggpubr)

barwidth = 0.5

# 1. make category plot
cat_plot_2 <- spp_summary %>% 
  group_by(phylum, category) %>%
  summarise(perc_cat = n()) %>%
  arrange(phylum) %>%
  mutate(perc_cat = round(perc_cat/sum(perc_cat)*100,2)) %>%
  ungroup()

## reorder factor
cat_plot_2$category <- forcats::as_factor(cat_plot_2$category)
levels(cat_plot_2$category)
cat_plot_2$category <- fct_relevel(cat_plot_2$category, "None","DD","LC","NT","VU","EN","CR")

## convert phylum to title case
cat_plot_2$phylum <- str_to_title(cat_plot_2$phylum)

threats_palette <- c("grey50","#bdbdbd","#fef0d9","#fdcc8a","#fc8d59","#e34a33","#b30000")

gg_cats_2 <- ggplot(data = cat_plot_2) +
  # plot phylum alphabetically from top, with black lines around bars
  geom_bar(aes(x= fct_rev(phylum), y=perc_cat, fill=category), 
           colour="black", size = 0.1, position="fill", stat="identity", width = barwidth) +
  scale_y_continuous('',labels = percent, expand = c(0,0)) +
  # colors for 7 levels 
  scale_fill_manual(values = threats_palette,
                    # labels = c("CR","EN","VU","NT","LC","DD","NA"),
                    labels = c("NA","DD","LC","NT","VU","EN","CR"),
                    guide = guide_legend(reverse= TRUE)) +
  coord_flip() +
  labs(x = NULL, fill = "Threat\nstatus") +
  theme(panel.grid.minor = element_blank(),
        panel.background = element_blank(),
         panel.grid.major = element_blank(),
         #panel.border = element_rect(colour = "black", size = 1, fill = NA),
         axis.title.y = element_blank(),
         axis.title.x = element_blank(),
         axis.ticks = element_blank(),
         legend.position = "right",
         #legend.position = "none",
         plot.margin= unit(c(1, 1, 1, 1), "lines"))
# extract legend
leg_cats <- get_legend(gg_cats_2)
# Convert to a ggplot and print
ggpubr::as_ggplot(leg_cats)
# then replot with legend suppressed

# 2. make eez plot
eez_plot <- spp_summary %>% 
  group_by(phylum, eez_bins_2) %>%
  summarise(perc_eez = n()) %>%
  group_by(phylum) %>%
  mutate(perc_eez = perc_eez/sum(perc_eez)*100)

eez_plot$eez_bins_2 <- forcats::as_factor(eez_plot$eez_bins_2)
levels(eez_plot$eez_bins_2)

## convert phylum to title case
eez_plot$phylum <- str_to_title(eez_plot$phylum)

gg_eez_2 <- ggplot(data = eez_plot) +
  # plot phylum alphabetically from top, with black lines around bars
  geom_bar(aes(x= fct_rev(phylum), y=perc_eez, fill=eez_bins_2), 
           colour="black", position="fill", stat="identity", width = barwidth, size = 0.1) +
  scale_y_continuous('',labels = percent, expand = c(0,0)) +
  # colors for 7 levels 
  scale_fill_manual(values = c("navyblue","royalblue3","dodgerblue1","deepskyblue1","skyblue1","lightblue1"),
                    labels = c("51-220","25-50","10-24","3-9","2","1"),
                    guide = guide_legend(reverse= TRUE)) + 
  coord_flip() +
  labs(x = NULL, fill = "Number\nEEZs") +
  theme(panel.grid.minor = element_blank(),
         panel.grid.major = element_blank(),
         panel.background = element_blank(),
         #panel.border = element_rect(colour = "black", size = 1, fill = NA),
         axis.title.y = element_blank(),
         axis.title.x = element_blank(),
         axis.ticks = element_blank(),
         legend.position = "right",
         #legend.position = "none",
         plot.margin= unit(c(1, 1, 1, 1), "lines")
        )

# extract legend
leg_eezs <- get_legend(gg_eez_2)
# Convert to a ggplot and print
ggpubr::as_ggplot(leg_eezs)
# then replot with legend suppressed



#<><>< Another attempt

# make a numeric phylum number
phylum_number <- eez_plot %>%
  distinct(phylum) %>%
  arrange(phylum) 
phylum_number$phylum_id <- seq.int(nrow(phylum_number))

threats_palette <- c("white","#bdbdbd","#fef0d9","#fdcc8a","#fc8d59","#e34a33","#b30000")

eez_plot <- left_join(eez_plot, phylum_number, by = "phylum")
cat_plot_2 <- left_join(cat_plot_2, phylum_number, by = "phylum")

barwidth = 0.4

gg_combined <- ggplot() +
  geom_bar(data = eez_plot,
           mapping = aes(x= phylum_id, y=perc_eez, fill= eez_bins_2), #colour="black", 
           position="stack", stat="identity", width = barwidth) +
  geom_bar(data = cat_plot_2,
           mapping = aes(x= phylum_id + barwidth, y=perc_cat, fill= category), 
           position="stack", stat="identity", width = barwidth) +
  scale_fill_manual(values = c("navyblue","royalblue3","dodgerblue1","deepskyblue1","skyblue1","lightblue1", 
                               threats_palette),
                    labels = c("51-220","25-50","10-24","3-9","2","1","NA","DD","LC","NT","VU","EN","CR"),
                    guide = guide_legend(reverse= FALSE)) + 
  # when adding the second bar, the order of fills/colors get messed up... not sure how to fix that 
  scale_y_continuous('',labels = percent, expand = c(0,0)) +
  scale_x_reverse() + 
  labs(x = NULL, fill = NULL) +
  coord_flip() +
  theme(panel.grid.minor = element_blank(),
         panel.grid.major = element_blank(),
         panel.background = element_blank(),
         panel.border = element_rect(colour = "black", size = 1, fill = NA),
         axis.title.y = element_blank(),
         axis.title.x = element_blank(),
         axis.ticks = element_blank(),
         legend.position = "right",
         #legend.position = "none",
         plot.margin= unit(c(1, 1, 1, 1), "lines")
        )


#<><><><><> A few tweaks:
## no space between bars
## some different coloring

threats_palette <- c("white","#bdbdbd","#fef0d9","#fdcc8a","#fc8d59","#e34a33","#b30000")
barwidth = 0.4

cat_plot_2$dummy <- 100

gg_cats_3 <- ggplot(data = cat_plot_2) +
  geom_bar(mapping = aes(x= fct_rev(phylum), y=perc_cat, fill=category), 
           #colour="black", 
           position="fill", stat="identity", width = barwidth) +
  scale_y_continuous('',labels = percent, expand = c(0,0)) +
  scale_fill_manual(values = threats_palette,
                    labels = c("NA","DD","LC","NT","VU","EN","CR"),
                    guide = guide_legend(reverse= TRUE)) +
  geom_bar(mapping = aes(x= fct_rev(phylum), y= dummy), 
           position="fill", stat="identity", width = barwidth) + 
  coord_flip() +
  labs(x = NULL, fill = "Threat\nstatus") +
  theme(panel.grid.minor = element_blank(),
        panel.background = element_blank(),
         panel.grid.major = element_blank(),
         panel.border = element_rect(colour = "black", size = 1, fill = NA),
         axis.title.y = element_blank(),
         axis.title.x = element_blank(),
         axis.ticks = element_blank(),
         #legend.position = "right",
         legend.position = "none",
         plot.margin= unit(c(1, 1, 1, 1), "lines"))
## this doesn't work... 


```


## Option 5: Butterfly/pyramid (2 side) percentage bar plot

x axis: percent of species in phylum
y axis: phylum
right panel color/fill: # of EEZs (bins)
left panel color/fill: Threat category

```{butterfly plot}

## Load species summary
spp_summary <- fread("R://TRANSSPP-A2259//tb_spp_v04//combined_spp_summary.csv")
names(spp_summary)
summary(spp_summary) # Max == 220
unique(spp_summary$category)

# make bins 
spp_summary$eez_bins_1 <- cut(spp_summary$num_eez, 
                              breaks = c(1,2,3,10,20,100,221), 
                            include.lowest = TRUE, right = FALSE, ordered_result = TRUE) # lowest breaks val should be included; breaks closed on right& open on left 

# make other bins 
spp_summary$eez_bins_2 <- cut(spp_summary$num_eez, 
                              breaks = c(1,2,3,10,25,51,221), 
                            include.lowest = TRUE, right = FALSE, ordered_result = TRUE)
# 2 countries: bilateral agreement (unless one is ABNJ...)
# 3-9 = straddling stocks, eg. Convention on the Conservation and Management of Pollock Resources in the Central Bering Sea (CCBSP) - 6 countries, or multilateral partnership e.g. Coral Triangle Initiative (6 countries)
# 10 - 24 = regional seas organizations (e.g. OSPAR has 15 countries) or smaller RFMOs (General Fisheries Commission for the Mediterranean = 24 countries)
# big RFMOs (e.g. ICCAT = 48 member countries, IOTC = 31 countries, CCAMLR = 26 members + 10 acceding countries)

#check bins
table(spp_summary$eez_bins_1) # n = 2691 in 1 eez
table(spp_summary$eez_bins_2) 

## make plot dat with percentages by threat group

plotdat_threats <- spp_summary %>% 
  group_by(phylum, category) %>%
  summarise(perc_cat = n()) %>%
  group_by(phylum) %>%
  mutate(perc_cat = round(perc_cat/sum(perc_cat)*100,2))
## reorder factor
plotdat_threats$category <- forcats::as_factor(plotdat_threats$category)
levels(plotdat_threats$category)
plotdat_threats$category <- fct_relevel(plotdat_threats$category, "CR","EN","VU","NT","LC","DD","None")

## make plot dat with percentages by eez bins

plotdat_eezs <- spp_summary %>% 
  group_by(phylum, eez_bins_2) %>%
  summarise(perc_eez = n()) %>%
  group_by(phylum) %>%
  mutate(perc_eez = perc_eez/sum(perc_eez)*100)

plotdat_eezs$eez_bins_2 <- forcats::as_factor(plotdat_eezs$eez_bins_2)
levels(plotdat_eezs$eez_bins_2)

#<><><><><><>
## PLOT

library(cowplot)
library(gridExtra)
library(RColorBrewer)

#### 1. "eez bins" plot - to appear on the right

gg_eezs <- ggplot(data = plotdat_eezs) +
  # plot phylum alphabetically from top
  geom_bar(aes(x= fct_rev(phylum), y=perc_eez, fill = forcats::fct_rev(eez_bins_2)), 
           colour = "black", position = "fill", stat = "identity") +
  scale_y_continuous(labels = scales::percent_format(), expand = c(0,0)) + 
  scale_fill_manual(values = c("mediumblue","dodgerblue1","deepskyblue1","skyblue1","lightblue1","grey70"),
                    labels = c("51-220","25-50","10-24","3-9","2","1"),
                    guide = guide_legend(reverse= TRUE)) +
  coord_flip() +
  labs(x = "Threat category", y = "Percent of species", fill = "Number of\nEEZs") +
  theme(panel.grid.minor = element_blank(),
         panel.grid.major = element_blank(),
         axis.text.y = element_blank(),
         axis.title.y = element_blank(),
         axis.title.x = element_blank(),
         # plot.title = element_text(size = 10, hjust = 0.5),
         axis.ticks = element_blank(),
         legend.position = "bottom",
         # legend.position = "none",
         plot.margin= unit(c(1, 0, 0, 0), "lines"))

# extract legend
leg_eezs <- get_legend(gg_eezs)
# Convert to a ggplot and print
as_ggplot(leg_eezs)
# then replot with legend suppressed


### Phylum labels - create plot using geom_text to appear down middle

fontsize = 2
gg_phylum <- ggplot(data = plotdat_eezs, aes(x= fct_rev(phylum))) +
   geom_bar(stat = "identity", aes(y = 0)) +
   geom_text(aes(y = 0,  label = phylum), size = fontsize) +
   # ggtitle("Phylum") +
   coord_flip() + 
   theme_bw() +
   theme(panel.border = element_rect(colour = NA),
         # legend.position = "none",
         panel.grid.minor = element_blank(),
         panel.grid.major = element_blank(), 
         axis.text.y = element_blank(), 
         axis.title.y = element_blank(),
         axis.title.x = element_blank(),
         axis.text.x = element_blank(),
         axis.ticks = element_blank(),
         legend.position = "bottom"
         )


#### Arrange the components

plot_grid(gg_cats, gg_phylum, gg_eezs, 
          align = "v", 
          nrow = 1,
          rel_heights = c(1, 3/4, 1), # works for widths but not heights
          rel_widths = c(3/4, 1/4, 3/4))


## do in photoshop. 
ggsave(plot = last_plot(), filename = "_results\figs\analysis_v04\fig_phyla_butterfly.png", width = 6, height = 3, units = "in")
ggsave(plot = gg_cats, filename = "_results\figs\analysis_v04\fig_phyla_cats.png", width = 5, height = 5, units = "in")
ggsave(plot = gg_eezs, filename = "_results\figs\analysis_v04\fig_phyla_eezs.png", width = 5, height = 5, units = "in")
ggsave(leg_cats, filename = "_results\figs\analysis_v04\fig_phyla_cats_legend.png")
ggsave(leg_eezs, filename = "_results\figs\analysis_v04\fig_phyla_eezs_legend.png")

## alphabetical list of phyla

phyla <- fread("R://TRANSSPP-A2259//tb_spp_v04//combined_spp_summary.csv") %>%
  distinct(phylum) %>%
  arrange(phylum)
```

## option 4 scatterplot (maybe second panel with percentage plot?)

```{simple scatterplot}

spp_summary <- fread("R://TRANSSPP-A2259//tb_spp_v04//combined_spp_summary.csv")
summary(spp_summary) # Max == 220

spp_summary$tax_group <- as_factor(spp_summary$tax_group)

sp <- ggplot(data = spp_summary) +
  geom_point(aes(x = species_id, y = num_eez, color = tax_group)) +
  labs(x = "Species", y = "Number of EEZs", fill = "Taxon\ngroup") +
  scale_color_manual(values = c("purple","blue","green")) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

# could fix this up but will probably still be illegible blob of dots
               
             
```

## Option 3: Single panel Percentage plot

Fig 1 in ms v1:
x-axis: threat status categories
y axis: percentage of species in that category

```{percentage plot}

## Load species summary

spp_summary <- fread("R://TRANSSPP-A2259//tb_spp_v04//combined_spp_summary.csv")
names(spp_summary)
summary(spp_summary) # Max == 220

## wrangle factors

unique(spp_summary$category)
# spp_summary$category <- spp_summary$category %>% fct_recode(None = "NA_AM")

# make bins 
spp_summary$eez_bins <- cut(spp_summary$num_eez, breaks = c(1,2,3,10,20,100,221), 
                            include.lowest = TRUE, right = FALSE, ordered_result = TRUE) # lowest breaks val should be included; breaks closed on right& open on left 

#check bins
table(spp_summary$eez_bins) # n = 2691 in 1 eez
table(spp_summary$xbd) # n = 2691 singlecountry

## make plot dat with percentages by threat group

plot_dat <- spp_summary %>% 
  group_by(category) %>%
  mutate(n=n(),
         prop_group = n() / first(n)*100) %>%
  dplyr::select(c(category, eez_bins, prop_group))

## reorder factor
plot_dat$category <- forcats::as_factor(plot_dat$category)
levels(plot_dat$category)
plot_dat$category <- fct_relevel(plot_dat$category, "CR","EN","VU","NT","LC","DD","None")

names(plot_dat)
#<><><><
## Plot

p <- ggplot(data = plot_dat) +
  geom_bar(aes(x=category, y=prop_group, fill = forcats::fct_rev(eez_bins)),
           position = "fill", stat = "identity") +
  scale_y_continuous(labels = scales::percent_format(), expand = c(0,0)) +
  scale_fill_manual(values = c("mediumblue","dodgerblue1","deepskyblue1","skyblue1","lightblue1","grey70"),
                    labels = c("100-220","20-99","10-19","3-9","2","1"),
                    guide = guide_legend(reverse= FALSE)) +
  labs(x = "Threat category", y = "Percent of species", fill = "Number of\nEEZs") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank())
p
  
## Save plot
ggsave("_results/figs/analysis_v04/perc_threatcats.png", width = 4, height = 4, units = "in")

## Save plot dat

```

## Option 2: percentages on y axis 

Percentage of total number of species

```{percentages on y axis}

## Load data

spp_summary <- fread("R://TRANSSPP-A2259//transboundary_species_v02//combined_spp_summary.csv")

names(spp_summary)
str(spp_summary)
unique(spp_summary$category)

spp_summary %>%
  ggplot(aes(x = category, fill = xbd)) +
  geom_bar(aes(y = (..count..)/sum(..count..)))

ggsave("_results/figs/fig1_species/threatcats_props_v01.png", width = 3, height = 4, units = "in")


n_distinct(spp_summary$species_id) # n = 32726

ggplot(data = spp_summary, 
       mapping = aes(x = num_countries, fill = xbd)) + 
  geom_bar(position = "dodge",
    mapping = aes(y = ..count../32726)) + # the .. is so "count" doesn't get confused if you've (stupidly) named a column count (same for ..prop..)
  scale_y_continuous(labels=scales::percent) +
  scale_x_continuous(limits = c(0,208), breaks = seq(0,200,25)) +
  labs(x = "number of EEZs", y = "percent of all species") + 
  theme_bw() +
  theme(legend.position = c(0.75, 0.75),
        panel.grid = element_blank()) 

ggsave("_results/figs/fig1_species/eezs_props_v01.png", width = 4, height = 4, units = "in")

```

## Option 1: normal histogram (count species on y axis)

```{normal histogram}

## Load data

spp_summary <- fread("R://TRANSSPP-A2259//tb_spp_v04//combined_spp_summary.csv")
names(spp_summary)

## basic histogram
spp_summary %>%
  ggplot(aes(x = num_eez)) +
  geom_bar(stat = "count")

##  stacked bar by taxon group 

plotdat <- spp_summary
plotdat$tax_group <- as.factor(plotdat$tax_group)
plotdat$tax_group <- fct_relevel(plotdat$tax_group, "Plant","Invertebrate","Vertebrate")

plotdat %>%
  count(num_countries, tax_group) %>%
  ggplot(aes(x = num_countries, y = n, fill = tax_group)) + 
  geom_bar(stat= "identity") +
  scale_y_continuous(limits = c(0,3500), breaks = seq(0,3000,500)) +
  scale_x_continuous(limits = c(0,200), breaks = seq(0,200,25)) +
  labs(y = "Number of species", x = "Number of jurisdictions") + 
  theme_bw() +
  theme(legend.position = c(0.75, 0.75),
        legend.title = element_blank())

## stacked bar by redlist category

plotdat$category <- as.factor(plotdat$category)
levels(plotdat$category)

plotdat$category_grouped <- plotdat$category %>%
  fct_collapse(Threatened = c("CR","EN","VU"),
               Not_threatened = c("LC","LR","NT"),
               Unknown = c("DD","NA_AM"))

plotdat$category_grouped <- fct_relevel(plotdat$category_grouped, "Threatened","Not_threatened","Unknown")

plotdat %>%
  count(num_countries, category_grouped) %>%
  ggplot(aes(x = num_countries, y = n, fill = category_grouped)) + 
  geom_bar(stat= "identity") +
  scale_y_continuous(limits = c(0,3500), breaks = seq(0,3000,500)) +
  scale_x_continuous(limits = c(0,200), breaks = seq(0,200,25)) +
  labs(y = "Number of species", x = "Number of jurisdictions", fill = "Conservation\nStatus") + 
  theme_bw() +
  theme(legend.position = c(0.75, 0.75))

spp_summary %>% group_by(species_id) %>% arrange(num_countries)
summary(spp_summary) # min nu countries == 1(good no zeros) and max == 207 

```
